rename person to spending
AY1920S1-CS2103T-F13-3/main pull request #54
Opened 2019-10-09 17:22 UTC by austinsantoso

Rename all instance of person to spending

2019-10-10 16:11 UTC, Nanosync requested changes
accidental

2019-10-10 16:11 UTC, Nanosync commented on LICENSE
> +Permission is hereby granted, free of charge, to any person obtaining a copy
accidental change

2019-10-10 16:11 UTC, Nanosync commented on docs/templates/LICENSE
> +Permission is hereby granted, free of charge, to any person obtaining a copy
ditto

2019-10-10 16:19 UTC, austinsantoso commented on LICENSE
> +Permission is hereby granted, free of charge, to any person obtaining a copy
isn't this correct, i changed the spending to person?

2019-10-10 16:29 UTC, Nanosync requested changes
last minor change before merge

2019-10-10 16:29 UTC, Nanosync commented on src/main/java/seedu/address/model/spending/Spending.java
> +        return Objects.hash(name, phone, email, tags);
address field accidentally removed from hash

2019-10-10 17:51 UTC, Nanosync approved these changes
Thank you Austin!

2019-10-10 17:52 UTC, merged

2019-10-17 15:28 UTC, choongyx commented
#10, #8, #9