update user guide with budget
AY1920S1-CS2103T-F13-3/main pull request #80
Opened 2019-10-18 09:47 UTC by austinsantoso

updated user guide with showbudget and removed prefix reuirement m/ for budget

2019-10-18 11:22 UTC, choongyx approved these changes

2019-10-18 11:22 UTC, choongyx commented on docs/UserGuide.adoc
> +Returns the currently set monthly budget. +
current monthly budget

2019-10-24 09:54 UTC, Nanosync requested changes
based on yong xin's changes

2019-10-24 10:06 UTC, Nanosync approved these changes

2019-10-24 10:10 UTC, merged